Added exception handling to mash.rb
In order to work through a bug that was preventing a client.get '/services/data/v33.0/analytics/dashboards/FFF', added exception handling to mash.rb starting at line 29. Previously, the following hard error was thrown: NoMethodError: undefined method `[]' for nil:NilClass (mash.rb:29:in `klass'). 

It now defaults to SObject on exception. The val.has_key? 'attributes' should have prevented this, but for some reason it's not. has_key? has been deprecated in favor of key? (http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/43765), which I changed as well (24 & 28), but that doesn't affect anything.